version: '3.8'

networks:
  wiki-streaming-network:
    name: wiki-streaming-network
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - wiki-streaming-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - ./scripts/init-kafka.sh:/scripts/init-kafka.sh
    healthcheck:
        test: ["CMD", "bash", "/scripts/init-kafka.sh"]
        interval: 5s
        timeout: 10s
        retries: 10
    networks:
      - wiki-streaming-network
    depends_on:
      - zookeeper


  spark:
    image: docker.io/bitnami/spark:3
    container_name: spark-master-server
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
        interval: 5s
        timeout: 3s
        retries: 3
    ports:
      - '8080:8080'
    networks:
      - wiki-streaming-network

  spark-worker:
    image: docker.io/bitnami/spark:3
    container_name: spark-worker-server
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_INSTANCES = 2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_ZOS_MASTER_APP_ALWAYSSCHEDULEAPPS=true  
    networks:
      - wiki-streaming-network

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra-server
    ports:
      - "9042:9042"
    volumes:
      - ./scripts/ddl.cql:/docker-entrypoint-initdb.d/ddl.cql
    environment:
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
    healthcheck:
          test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE wiki;'" ]
          interval: 5s
          retries: 20
          timeout: 5s
    networks:
      - wiki-streaming-network


  endpoint-reader:
    image: endpoint-reader-app
    container_name: endpoint-reader-server
    build:
      context: ./endpoint-reader-app
    environment:
      - KAFKA_TOPIC=input
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./endpoint-reader-app:/app
    networks:
      - wiki-streaming-network
    depends_on:
      kafka:
        condition: service_healthy

  cassandra-populating:
    image: cassandra-populating-app
    container_name: cassandra-populating-server
    build:
      context: ./cassandra-populating-app
    volumes:
      - ./cassandra-populating-app:/app
    networks:
      - wiki-streaming-network
    depends_on:
      kafka:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      spark:
        condition: service_healthy
      spark-worker:
        condition: service_started

  rest-app:
    image: rest-app
    container_name: rest-app-server
    build:
      context: ./rest-app
    ports:
      - "4200:4200"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=wiki
      - APP_PORT=4200
      - APP_HOST=0.0.0.0
    networks:
      - wiki-streaming-network
    depends_on:
      cassandra:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - wiki-streaming-network

volumes:
  mongodb-data:
